# Generated by Django 3.2.13 on 2022-06-12 02:24

from django.db import migrations, models
import django.db.models.deletion
import nejdej.utils.storages


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, storage=nejdej.utils.storages.ListingImageStorage(), upload_to='')),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published'), ('DN', 'Denied')], editable=False, help_text=[('DF', 'Draft'), ('PB', 'Published'), ('DN', 'Denied')], max_length=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.subcategory')),
            ],
            options={
                'verbose_name': 'Listing',
                'verbose_name_plural': 'Listings',
            },
        ),
    ]
