# Generated by Django 4.0.5 on 2022-07-03 21:09

from django.db import migrations, models
import django.db.models.deletion
import nejdej.utils.storages


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='image',
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(storage=nejdej.utils.storages.ListingImageStorage(), upload_to='')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_images', to='listings.listing')),
            ],
            options={
                'verbose_name': 'Listing Image',
                'verbose_name_plural': 'Listing Images',
            },
        ),
    ]
