/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * Nejdej API
 * Documentation of API endpoints of Nejdej
 * OpenAPI spec version: 1.0.0
 */

export type ApiListingsListParams = { category_slug?: string; description_search?: string; itemsPerPage?: number; ordering?: string; page?: number; search?: string; status?: string[]; sub_category_slug?: string; title_search?: string };
