/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * Nejdej API
 * Documentation of API endpoints of Nejdej
 * OpenAPI spec version: 1.0.0
 */

export interface Category {
  slug: string;
  readonly created_at: string;
  readonly updated_at: string;
  name: string;
  description?: string | null;
  image?: string | null;
  is_active?: boolean;
}
