/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * Nejdej API
 * Documentation of API endpoints of Nejdej
 * OpenAPI spec version: 1.0.0
 */

export interface ListingUserRequest {
  first_name?: string;
  last_name?: string | null;
  image?: Blob | null;
}
