/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * Nejdej API
 * Documentation of API endpoints of Nejdej
 * OpenAPI spec version: 1.0.0
 */
import type { ListingView } from './listingView';
import type { ListingImage } from './listingImage';
import type { ListingUser } from './listingUser';

export interface Listing {
  readonly id: string;
  readonly views: ListingView;
  listing_images: ListingImage[];
  readonly user: ListingUser;
  title: string;
  description?: string | null;
  /** [('DF', 'Draft'), ('PB', 'Published'), ('DN', 'Denied')] */
  readonly status: string;
  price: string;
  sub_category: string;
}
