/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * Nejdej API
 * Documentation of API endpoints of Nejdej
 * OpenAPI spec version: 1.0.0
 */
import type { Listing } from './listing';

export interface PaginatedListingList {
  count?: number;
  next?: string | null;
  previous?: string | null;
  results?: Listing[];
}
