/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * Nejdej API
 * Documentation of API endpoints of Nejdej
 * OpenAPI spec version: 1.0.0
 */
import type { Review } from './review';

export interface PaginatedReviewList {
  count?: number;
  next?: string | null;
  previous?: string | null;
  results?: Review[];
}
