/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * Nejdej API
 * Documentation of API endpoints of Nejdej
 * OpenAPI spec version: 1.0.0
 */

/**
 * Serializer for requesting a password reset e-mail.
 */
export interface PasswordResetRequest {
  email: string;
}
