/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * Nejdej API
 * Documentation of API endpoints of Nejdej
 * OpenAPI spec version: 1.0.0
 */

export interface PatchedListingRequest {
  id?: string;
  title?: string;
  description?: string | null;
  image?: Blob | null;
  price?: string;
  user?: number;
  sub_category?: string;
}
