/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * Nejdej API
 * Documentation of API endpoints of Nejdej
 * OpenAPI spec version: 1.0.0
 */

export interface SocialLogin {
  access_token?: string;
  code?: string;
  id_token?: string;
}
