/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * Nejdej API
 * Documentation of API endpoints of Nejdej
 * OpenAPI spec version: 1.0.0
 */

export interface SubCategoryRequest {
  slug: string;
  name: string;
  description?: string | null;
  image?: Blob | null;
  is_active?: boolean;
  category: string;
}
