/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * Nejdej API
 * Documentation of API endpoints of Nejdej
 * OpenAPI spec version: 1.0.0
 */
import {
  rest
} from 'msw'
import {
  faker
} from '@faker-js/faker'

export const getRestAuthFacebookCreateMock = () => ({key: faker.random.word()})

export const getRestAuthGoogleCreateMock = () => ({key: faker.random.word()})

export const getRestAuthMSW = () => [
rest.post('*/rest-auth/facebook', (_req, res, ctx) => {
        return res(
          ctx.delay(1000),
          ctx.status(200, 'Mocked status'),
ctx.json(getRestAuthFacebookCreateMock()),
        )
      }),rest.post('*/rest-auth/google', (_req, res, ctx) => {
        return res(
          ctx.delay(1000),
          ctx.status(200, 'Mocked status'),
ctx.json(getRestAuthGoogleCreateMock()),
        )
      }),]
