# Generated by Django 3.2.13 on 2022-05-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListingView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_name', models.SlugField(default='', max_length=200, unique=True)),
                ('daily', models.IntegerField(default=0)),
                ('weekly', models.IntegerField(default=0)),
                ('monthly', models.IntegerField(default=0)),
                ('yearly', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Listing View',
                'verbose_name_plural': 'Listing Views',
            },
        ),
    ]
