# Generated by Django 3.2.13 on 2022-05-20 01:00

from django.db import migrations, models
import nejdej.utils.storages


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, storage=nejdej.utils.storages.UserAvatarStorage(), upload_to=''),
        ),
    ]
